"""SSL keys model

Revision ID: 12edd6e32e34
Revises: 3c70b82ce4e8
Create Date: 2015-09-15 20:49:55.501088

"""

# revision identifiers, used by Alembic.
revision = '12edd6e32e34'
down_revision = '3c70b82ce4e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('ssl_keys',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=255), nullable=True),
    # sa.Column('domaincontroller_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['domaincontroller_id'], ['domain_controller.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name', 'domaincontroller_id', name='_ssl_dc_uc')
    # )
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('ssl_keys')
    ### end Alembic commands ###
