"""adding SSL upload

Revision ID: 1bb6b37ea33a
Revises: 2b6315172fd1
Create Date: 2015-06-18 19:08:29.640227

"""

# revision identifiers, used by Alembic.
revision = '1bb6b37ea33a'
down_revision = '2b6315172fd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssl_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('domaincontroller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domaincontroller_id'], ['domain_controller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'domain', 'domain_controller', ['domain_controller_id'], ['id'])
    op.create_foreign_key(None, 'upstream', 'domain', ['domain_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upstream', type_='foreignkey')
    op.drop_constraint(None, 'domain', type_='foreignkey')
    op.drop_table('ssl_keys')
    ### end Alembic commands ###
