"""vagrant_instance.archive_url

Revision ID: 28746053e322
Revises: 3787ddc53c21
Create Date: 2014-11-21 20:02:51.919751

"""

# revision identifiers, used by Alembic.
revision = '28746053e322'
down_revision = '3787ddc53c21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vagrant_instance', sa.Column('archive_url', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vagrant_instance', 'archive_url')
    ### end Alembic commands ###
