"""Adding domain aliases

Revision ID: 2b6315172fd1
Revises: 28746053e322
Create Date: 2014-12-04 15:52:31.083532

"""

# revision identifiers, used by Alembic.
revision = '2b6315172fd1'
down_revision = '28746053e322'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=255), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alias')
    ### end Alembic commands ###
