"""api key model

Revision ID: 2d47b5315653
Revises: 12edd6e32e34
Create Date: 2015-09-15 21:22:04.531031

"""

# revision identifiers, used by Alembic.
revision = '2d47b5315653'
down_revision = '12edd6e32e34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    ### end Alembic commands ###
