"""empty message

Revision ID: 342272fcff6
Revises: 28746053e322
Create Date: 2015-01-21 19:53:41.556811

"""

# revision identifiers, used by Alembic.
revision = '342272fcff6'
down_revision = '28746053e322'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_controller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('port', sa.String(length=4), nullable=True),
    sa.Column('accept_self_signed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SSL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('domaincontroller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domaincontroller_id'], ['domain_controller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(u'domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain_controller_id', sa.Integer(), nullable=True))

    with op.batch_alter_table(u'upstream', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Enum('up', 'down', 'backup'), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'upstream', schema=None) as batch_op:
        batch_op.drop_column('state')

    with op.batch_alter_table(u'domain', schema=None) as batch_op:
        batch_op.drop_column('domain_controller_id')

    op.drop_table('SSL')
    op.drop_table('domain_controller')
    ### end Alembic commands ###
