"""empty message

Revision ID: 3787ddc53c21
Revises: 77f60cf3876
Create Date: 2014-11-18 23:10:42.045160

Missing column for the last revision
"""

# revision identifiers, used by Alembic.
revision = '3787ddc53c21'
down_revision = '77f60cf3876'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('domain_controller_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain', 'domain_controller_id')
    ### end Alembic commands ###
