"""empty message

Revision ID: 3c70b82ce4e8
Revises: 40c2706bfd53
Create Date: 2015-06-26 21:12:24.962900

"""

# revision identifiers, used by Alembic.
revision = '3c70b82ce4e8'
down_revision = '40c2706bfd53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upstream', sa.Column('location', sa.String(length=254), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upstream', 'location')
    ### end Alembic commands ###
