"""empty message

Revision ID: 40c2706bfd53
Revises: 2b6315172fd1
Create Date: 2015-06-26 19:05:00.989278

"""

# revision identifiers, used by Alembic.
revision = '40c2706bfd53'
down_revision = '2b6315172fd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'domain', 'domain_controller', ['domain_controller_id'], ['id'])
    op.add_column('upstream', sa.Column('websocket', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'upstream', 'domain', ['domain_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upstream', type_='foreignkey')
    op.drop_column('upstream', 'websocket')
    op.drop_constraint(None, 'domain', type_='foreignkey')
    ### end Alembic commands ###
