"""empty message

Revision ID: 51b66b3d835a
Revises: 38e1ae266dbf
Create Date: 2014-10-23 17:37:34.452627

"""

# revision identifiers, used by Alembic.
revision = '51b66b3d835a'
down_revision = '38e1ae266dbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upstream', sa.Column('port_ssl', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upstream', 'port_ssl')
    ### end Alembic commands ###
