"""upstream state

Revision ID: 522a1ad5eb0c
Revises: 51b66b3d835a
Create Date: 2014-11-18 18:51:55.571678

"""

# revision identifiers, used by Alembic.
revision = '522a1ad5eb0c'
down_revision = '51b66b3d835a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upstream', sa.Column('state', sa.Enum('up', 'down', 'backup'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upstream', 'state')
    ### end Alembic commands ###
