"""Audit logs

Revision ID: 52a334296cc0
Revises: 32b2ac4e1f58
Create Date: 2015-09-29 16:39:26.076968

"""

# revision identifiers, used by Alembic.
revision = '52a334296cc0'
down_revision = '32b2ac4e1f58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobid', sa.Integer(), nullable=True),
    sa.Column('objectId', sa.Integer(), nullable=True),
    sa.Column('objectName', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    ### end Alembic commands ###
