"""Create table Domain

Revision ID: 567ffa3f5475
Revises: 3e52765e7151
Create Date: 2014-10-09 14:28:10.520956

"""

# revision identifiers, used by Alembic.
revision = '567ffa3f5475'
down_revision = '3e52765e7151'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=255), nullable=True),
    sa.Column('htpasswd', sa.String(length=128), nullable=True),
    sa.Column('ssl_key', sa.String(length=128), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upstream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=32), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upstream')
    op.drop_table('domain')
    ### end Alembic commands ###
