"""SSL keys constraint

Revision ID: 59194701b6e9
Revises: 1bb6b37ea33a
Create Date: 2015-06-25 14:09:34.199182

"""

# revision identifiers, used by Alembic.
revision = '59194701b6e9'
down_revision = '1bb6b37ea33a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_ssl_dc_uc', 'ssl_keys', ['name', 'domaincontroller_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_ssl_dc_uc', 'ssl_keys', type_='unique')
    ### end Alembic commands ###
