"""Add object type

Revision ID: 5a5346d9845d
Revises: 52a334296cc0
Create Date: 2015-09-29 18:50:38.151612

"""

# revision identifiers, used by Alembic.
revision = '5a5346d9845d'
down_revision = '52a334296cc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('objectType', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'objectType')
    ### end Alembic commands ###
